# Create VG and filesystems

# - name: Create data VG
#   lvg: vg={{ oracle_datavg }} pvs={{ oracle_disks }}

 - name: Create data volumes
   lvol: vg={{ oracle_datavg }} lv={{ item.fs_vol }} size={{ item.fs_size }}
   with_items: "{{ oracle_fs_list }}"

 - name: Format data filesystems
   filesystem: fstype=ext4 dev=/dev/mapper/{{ oracle_datavg }}-{{ item.fs_vol }} resizefs=yes opts="-m 1"
   with_items: "{{ oracle_fs_list }}"

 - name: Mount data filesystems
   mount: name={{ item.fs_mount }} src=/dev/mapper/{{ oracle_datavg }}-{{ item.fs_vol }} fstype=ext4 opts=defaults,noatime dump='1' passno='2' state=mounted
   with_items: "{{ oracle_fs_list }}"


# Permissions

 - name: Assign permissions
   file: path={{ item.fs_mount }} owner={{ oracle_user }} group={{ oracle_group }} mode=0755
   with_items: "{{ oracle_fs_list }}"

# Resize shared memory filesystem if needed

 - name: Resize /dev/shm
   mount: name=/dev/shm src=tmpfs fstype=tmpfs opts='defaults,size={{ oracle_memory | int + 10 }}%' state=mounted
   when: oracle_memory > 40
