# Users and groups

 - name: Create groups
   group: name={{ oracle_group }} state=present

 - name: Add extra groups
   group: name={{ item }} state=present
   with_items: "{{ oracle_groups }}"

 - name: Create user
   user: name={{ oracle_user }} group={{ oracle_group }} password={{ oracle_user_pass | password_hash('sha512') }} update_password=on_create home=/home/{{ oracle_user }} shell=/bin/bash

 - name: Add extra groups
   user: name={{ oracle_user }} groups={{ item }} append=yes
   with_items: "{{ oracle_groups }}"

