SELECT M.TABLESPACE_NAME TABLESPACE,
      trunc(D.TOTAL,2) ALLOCADO,
      trunc(USED_SPACE*value/1024/1024,2) OCUPADO,
      trunc(D.TOTAL,2)-trunc(USED_SPACE*value/1024/1024,2) LIBRE,
      round(USED_SPACE*value/1024/1024*100/d.total,2) POR_USED
 FROM DBA_TABLESPACE_USAGE_METRICS M, v$parameter, (
      SELECT TABLESPACE_NAME,SUM(BYTES/1024/1024) TOTAL
        FROM DBA_DATA_FILES D
    GROUP BY TABLESPACE_NAME) D
WHERE M.TABLESPACE_NAME=D.TABLESPACE_NAME
  AND name = 'db_block_size'
--  AND D.TABLESPACE_NAME LIkE UPPER('%T%')
ORDER BY 5 DESC
/
